apiVersion: v1
kind: Service
metadata:
  name: canary-svc
spec:
  type: ClusterIP
  selector:
    app: canary
    # version: "1.0"  #TODO Step 2 Comentamos está línea para que curl detecte v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80